"""empty message

Revision ID: caaefc07a27a
Revises: 
Create Date: 2018-10-14 11:50:44.222225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaefc07a27a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('kode', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NamaLengkap', sa.String(length=64), nullable=False),
    sa.Column('Gelar', sa.String(length=16), nullable=False),
    sa.Column('Jabatan', sa.String(length=32), nullable=True),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('Asesor',
    sa.Column('idAsesor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nama', sa.String(length=64), nullable=False),
    sa.Column('Gelar', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('idAsesor')
    )
    op.create_table('Pekerjaan',
    sa.Column('idPekerjaan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NamaPerusahaan', sa.String(length=128), nullable=False),
    sa.Column('Jabatan', sa.String(length=128), nullable=True),
    sa.Column('Alamat', sa.String(length=255), nullable=True),
    sa.Column('KodePos', sa.String(length=8), nullable=True),
    sa.Column('NoTelepon', sa.String(length=13), nullable=True),
    sa.Column('NoFax', sa.String(length=32), nullable=True),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('idPekerjaan')
    )
    op.create_table('UjiKompetensi',
    sa.Column('KodeUnit', sa.String(length=128), nullable=False),
    sa.Column('JudulUnit', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('KodeUnit')
    )
    op.create_table('ElemenKompetensi',
    sa.Column('idElemen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nama', sa.String(length=128), nullable=False),
    sa.Column('ujikompetensi', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ujikompetensi'], ['UjiKompetensi.KodeUnit'], ),
    sa.PrimaryKeyConstraint('idElemen')
    )
    op.create_table('Jurusan',
    sa.Column('idJurusan', sa.Integer(), nullable=False),
    sa.Column('Nama', sa.String(length=64), nullable=False),
    sa.Column('kompetensi', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['kompetensi'], ['UjiKompetensi.KodeUnit'], ),
    sa.PrimaryKeyConstraint('idJurusan')
    )
    op.create_table('Ujian',
    sa.Column('idUjian', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.Column('tempat', sa.String(length=32), nullable=True),
    sa.Column('ruang', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('asesor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesor'], ['Asesor.idAsesor'], ),
    sa.PrimaryKeyConstraint('idUjian')
    )
    op.create_table('Asesi',
    sa.Column('idAsesi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NamaLengkap', sa.String(length=64), nullable=False),
    sa.Column('TempatLahir', sa.String(length=255), nullable=False),
    sa.Column('JenisKelamin', sa.String(length=1), nullable=False),
    sa.Column('Kebangsaan', sa.String(length=64), nullable=False),
    sa.Column('Alamat', sa.String(length=255), nullable=False),
    sa.Column('KodePos', sa.String(length=8), nullable=False),
    sa.Column('NoHP', sa.String(length=13), nullable=False),
    sa.Column('NoHPRumah', sa.String(length=13), nullable=True),
    sa.Column('NoHPKantor', sa.String(length=13), nullable=True),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.Column('PendidikanTerakhir', sa.String(length=128), nullable=True),
    sa.Column('StatusKompeten', sa.Boolean(), nullable=True),
    sa.Column('StatusBekerja', sa.Boolean(), nullable=True),
    sa.Column('idPekerjaan', sa.Integer(), nullable=True),
    sa.Column('jurusan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPekerjaan'], ['Pekerjaan.idPekerjaan'], ),
    sa.ForeignKeyConstraint(['jurusan'], ['Jurusan.idJurusan'], ),
    sa.PrimaryKeyConstraint('idAsesi')
    )
    op.create_table('KUK',
    sa.Column('idKUK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pertanyaan', sa.String(length=255), nullable=False),
    sa.Column('elemen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elemen'], ['ElemenKompetensi.idElemen'], ),
    sa.PrimaryKeyConstraint('idKUK')
    )
    op.create_table('Pendaftaran',
    sa.Column('noPendaftaran', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('asesi', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['Admin.kode'], ),
    sa.ForeignKeyConstraint(['asesi'], ['Asesi.idAsesi'], ),
    sa.PrimaryKeyConstraint('noPendaftaran')
    )
    op.create_table('DetailUjian',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nilai', sa.Integer(), nullable=False),
    sa.Column('ujian', sa.Integer(), nullable=True),
    sa.Column('asesi', sa.Integer(), nullable=True),
    sa.Column('kuk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesi'], ['Pendaftaran.noPendaftaran'], ),
    sa.ForeignKeyConstraint(['kuk'], ['KUK.idKUK'], ),
    sa.ForeignKeyConstraint(['ujian'], ['Ujian.idUjian'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DetailUjian')
    op.drop_table('Pendaftaran')
    op.drop_table('KUK')
    op.drop_table('Asesi')
    op.drop_table('Ujian')
    op.drop_table('Jurusan')
    op.drop_table('ElemenKompetensi')
    op.drop_table('UjiKompetensi')
    op.drop_table('Pekerjaan')
    op.drop_table('Asesor')
    op.drop_table('Admin')
    # ### end Alembic commands ###
